# Project 配置文件
spring:
  # 应用名称
  application:
    name: web
  # 嵌入式数据库
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
      enabled: true
  # JPA 设置; dal-auto如果关了，就不会根据entity新建表了
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
  # 数据源设置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:../PackageTool/data/H2DataBase/h2db
    username: san
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



# 应用服务 WEB 访问端口
server:
  port: 19801
  ip: 0.0.0.0
  tomcat:
    max-swallow-size: 2000MB


# MP设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#log4j2配置文件
#logging:
#  config: classpath:log4j2.xml


#文件存储路径
files:
  upload:
    path: ../PackageTool/data/files
  temp:
    path: ../PackageTool/data/fileTemp
  zip:
    path: ../PackageTool/data/zips
  scheme:
    path: web/src/main/resources/scheme
  schemeDetail:
      path: web/src/main/resources/schemeDetailInfo

